name: Check unimplemented_v2 calls


on:
  pull_request:
    paths:
      - 'torch/_dynamo/**/*.py'

jobs:
  check-unimplemented-calls:
    if: github.repository_owner == 'pytorch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep '\.py$' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Check unimplemented_v2 calls
        run: |
          python tools/dynamo/gb_id_mapping.py check --files "${{ steps.changed-files.outputs.files }}" --registry-path tools/dynamo/graph_break_registry.json
        continue-on-error: true
        id: check-calls

      - name: Fail if unimplemented_v2 calls don't match registry
        if: steps.check-calls.outcome == 'failure'
        run: |
          echo "::error::Found unimplemented_v2 calls that don't match the registry."
          echo "::error::Please update the registry using one of these commands:"
          echo "::error::- Add new entry: python tools/dynamo/gb_id_mapping.py add \"GB_TYPE\" PATH_TO_FILE [--additional-info \"INFO\"]"
          echo "::error::- Update existing: python tools/dynamo/gb_id_mapping.py update \"GB_TYPE\" PATH_TO_FILE [--new_gb_type \"NEW_NAME\"] [--additional-info \"INFO\"]"
          echo "::error::- Recreate registry: python tools/dynamo/gb_id_mapping.py create"
          echo "::error::Note: If you've reset the entire registry file, you can force push to bypass this check."
          exit 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
